  // This file contains javascript vars that were created from running the compiler.py file on each csv file

  // BEGIN agg_sites_data
  let agg_sites_data = [
    {Name:"Run Washington - DC Area Race Calendar", Link:"https://www.runwashington.com/race-calendar/"}, 
    {Name:"City Cast DC - Daily Events List", Link:"https://dc.citycast.fm/events"}, 
    {Name:"Capitalbop - DC Jazz Calendar", Link:"https://www.capitalbop.com/dcjazzcalendar/"}, 
    {Name:"Ticketmaster - Sports Tickets", Link:"https://www.ticketmaster.com/discover/sports/washington"}
  ];
  // END agg_sites_data

// BEGIN events_by_month_data
let events_by_month_data = [
  {Month:"September", Category:"Sports", Free:"No", Name:"NFL Football Season - Washington Commanders", Link:"https://www.commanders.com/schedule/"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"NFL Football Season - Washington Commanders", Link:"https://www.commanders.com/schedule/"}, 
  {Month:"November", Category:"Sports", Free:"No", Name:"NFL Football Season - Washington Commanders", Link:"https://www.commanders.com/schedule/"}, 
  {Month:"December", Category:"Sports", Free:"No", Name:"NFL Football Season - Washington Commanders", Link:"https://www.commanders.com/schedule/"}, 
  {Month:"January", Category:"Sports", Free:"No", Name:"NFL Football Season - Washington Commanders", Link:"https://www.commanders.com/schedule/"}, 
  {Month:"February", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"August", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"September", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"MLB Baseball Season - Washington Nationals", Link:"https://www.mlb.com/nationals/schedule/"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"November", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"December", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"January", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"February", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"NHL Hockey Season - Washington Capitals", Link:"https://www.ticketmaster.com/washington-capitals-tickets/artist/806039?home_away=home"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"November", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"December", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"January", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"February", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"NBA Basketball Season - Washington Wizards", Link:"https://www.ticketmaster.com/washington-wizards-tickets/artist/806042?home_away=home"}, 
  {Month:"February", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"August", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"September", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"MLS Soccer Season - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"November", Category:"Sports", Free:"No", Name:"MLS Soccer Season Playoffs - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"December", Category:"Sports", Free:"No", Name:"MLS Soccer Season Playoffs - DC United", Link:"https://www.ticketmaster.com/d.c.-united-tickets/artist/806390?home_away=home"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"UFL Football Season - DC Defenders", Link:"https://www.ticketmaster.com/dc-defenders-tickets/artist/2666908?home_away=home"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"UFL Football Season - DC Defenders", Link:"https://www.ticketmaster.com/dc-defenders-tickets/artist/2666908?home_away=home"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"UFL Football Season - DC Defenders", Link:"https://www.ticketmaster.com/dc-defenders-tickets/artist/2666908?home_away=home"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"UFL Football Season - DC Defenders", Link:"https://www.ticketmaster.com/dc-defenders-tickets/artist/2666908?home_away=home"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"August", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"September", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"October", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"November", Category:"Sports", Free:"No", Name:"NWSL Soccer Season - Washington Spirit", Link:"https://www.ticketmaster.com/washington-spirit-tickets/artist/1840091?home_away=home"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"WNBA Basketball Season - Washington Mystics", Link:"https://www.ticketmaster.com/washington-mystics-tickets/artist/806040?home_away=home"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"WNBA Basketball Season - Washington Mystics", Link:"https://www.ticketmaster.com/washington-mystics-tickets/artist/806040?home_away=home"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"WNBA Basketball Season - Washington Mystics", Link:"https://www.ticketmaster.com/washington-mystics-tickets/artist/806040?home_away=home"}, 
  {Month:"August", Category:"Sports", Free:"No", Name:"WNBA Basketball Season - Washington Mystics", Link:"https://www.ticketmaster.com/washington-mystics-tickets/artist/806040?home_away=home"}, 
  {Month:"September", Category:"Sports", Free:"No", Name:"WNBA Basketball Season - Washington Mystics", Link:"https://www.ticketmaster.com/washington-mystics-tickets/artist/806040?home_away=home"}, 
  {Month:"September", Category:"Arts", Free:"Yes", Name:"Art All Night (DC)", Link:"https://www.dcartallnight.org/"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"MLR Rubgy Season - DC Old Glory", Link:"https://oldglorydc.com/tickets/"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"MLR Rubgy Season - DC Old Glory", Link:"https://oldglorydc.com/tickets/"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"MLR Rubgy Season - DC Old Glory", Link:"https://oldglorydc.com/tickets/"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"MLR Rubgy Season - DC Old Glory", Link:"https://oldglorydc.com/tickets/"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"MLC Cricket Season - Washington Freedom", Link:"https://tickets.majorleaguecricket.com/"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"MLC Cricket Season - Washington Freedom", Link:"https://tickets.majorleaguecricket.com/"}, 
  {Month:"February", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"March", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"April", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"May", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"June", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"July", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"August", Category:"Sports", Free:"No", Name:"DC Roller Derby", Link:"https://www.dcrollerderby.org/news-events/all-events/"}, 
  {Month:"January", Category:"Miscellaneous", Free:"No", Name:"Washington Auto Show", Link:"https://washingtonautoshow.com/"}, 
  {Month:"February", Category:"Miscellaneous", Free:"No", Name:"Washington Auto Show", Link:"https://washingtonautoshow.com/"}, 
  {Month:"March", Category:"Holiday", Free:"Yes", Name:"DC Saint Patricks Day Parade", Link:"https://dcstpatsparade.com/"}, 
  {Month:"March", Category:"Festivals", Free:"Yes", Name:"Cherry Blossom Festival", Link:"https://nationalcherryblossomfestival.org/"}, 
  {Month:"April", Category:"Festivals", Free:"Yes", Name:"Cherry Blossom Festival", Link:"https://nationalcherryblossomfestival.org/"}, 
  {Month:"April", Category:"Movies", Free:"Yes", Name:"DC Film Fest", Link:"https://www.filmfestdc.org/"}, 
  {Month:"April", Category:"Arts", Free:"Yes", Name:"Smithsonian Craft Show", Link:"https://smithsoniancraftshow.org/"}, 
  {Month:"May", Category:"Miscellaneous", Free:"Yes", Name:"Flower Mart at the Washington National Cathedral", Link:"https://allhallowsguild.org/programs/flower-mart/"}, 
  {Month:"May", Category:"Holiday", Free:"Yes", Name:"Memorial Day Parade", Link:"https://americanveteranscenter.org/avc-events/parade/"}, 
  {Month:"August", Category:"Festivals", Free:"No", Name:"Virginia Scottish Games", Link:"https://www.vascottishgames.org/"}, 
  {Month:"September", Category:"Festivals", Free:"Yes", Name:"Mosaic Fall Festival", Link:"https://mosaicdistrict.com/events/event/mosaic-fall-festival/"}, 
  {Month:"September", Category:"Arts", Free:"Yes", Name:"Occoquan's Fall Arts & Crafts Show", Link:"https://www.occoquanfestivals.com/fall"}, 
  {Month:"June", Category:"Arts", Free:"Yes", Name:"Occoquan Riverfest & Craft Festival", Link:"https://www.occoquanfestivals.com/riverfest"}, 
  {Month:"October", Category:"Holiday", Free:"No", Name:"Markoff's Haunted Forest", Link:"https://www.markoffshauntedforest.com/"}, 
  {Month:"September", Category:"Festivals", Free:"Yes", Name:"Rokeby Community Festival", Link:"https://www.osgf.org/programs-and-events-calendar"}, 
  {Month:"September", Category:"Holiday", Free:"No", Name:"Oktoberfests Around the DMV Area", Link:""}, 
  {Month:"March", Category:"Festivals", Free:"No", Name:"VA Irish Festival", Link:"https://www.vairishfest.com/"}, 
  {Month:"April", Category:"Festivals", Free:"Yes", Name:"Shenandoah Apple Blossom Festival", Link:"https://www.thebloom.com/"}, 
  {Month:"May", Category:"Festivals", Free:"Yes", Name:"Shenandoah Apple Blossom Festival", Link:"https://www.thebloom.com/"}, 
  {Month:"September", Category:"Festivals", Free:"Yes", Name:"Clarendon Day", Link:"https://www.clarendon.org/clarendon-day/"}, 
  {Month:"May", Category:"Miscellaneous", Free:"Yes", Name:"Clarendon Music by the Metro Shows", Link:"https://www.clarendon.org/music-by-the-metro/"}
];
// END events_by_month_data

// BEGIN food_and_music_data
let food_and_music_data = [
  {Mon:"", Tues:"", Wed:"Music", Thurs:"", Fri:"Music", Sat:"Music", Sun:"", Name:"Westover Beer Garden", Link:"http://www.westovermarketbeergarden.com/live-music.html"}, 
  {Mon:"", Tues:"Trivia", Wed:"EDM DJ", Thurs:"", Fri:"Traditional Irish Music", Sat:"Traditional Irish Music", Sun:"", Name:"The Auld Shebeen", Link:"https://theauldshebeenva.com/entertainment/"}, 
  {Mon:"See Schedule", Tues:"See Schedule", Wed:"See Schedule", Thurs:"See Schedule", Fri:"See Schedule", Sat:"See Schedule", Sun:"See Schedule", Name:"Bourbon Boulevard", Link:"https://www.bbcbar.com/events-1"}, 
  {Mon:"Open Mic", Tues:"", Wed:"Trivia, Music", Thurs:"Karaoke", Fri:"Karaoke", Sat:"Karaoke", Sun:"", Name:"Fat's Fairfax", Link:"https://www.fats-fairfax.com/"}, 
  {Mon:"", Tues:"Traditional Irish Music", Wed:"", Thurs:"", Fri:"Music", Sat:"Music", Sun:"", Name:"Ireland's Four Provinces", Link:"http://www.4psva.com/event"}, 
  {Mon:"Music", Tues:"Music", Wed:"Music", Thurs:"Music", Fri:"Music", Sat:"Music", Sun:"Music", Name:"JV's Restaurant", Link:"http://www.jvsrestaurant.com/calendar"}, 
  {Mon:"Football", Tues:"Latin Dancing", Wed:"Karaoke", Thurs:"Trivia, Football", Fri:"Music", Sat:"", Sun:"", Name:"Kalypso's Sports Tavern", Link:"https://www.kalypsossportstavern.com/events"}, 
  {Mon:"", Tues:"", Wed:"", Thurs:"Trivia", Fri:"", Sat:"", Sun:"", Name:"Mustang Sally Brewing", Link:"https://www.msbrewing.com/taproom/events"}, 
  {Mon:"", Tues:"", Wed:"Trivia", Thurs:"Line Dancing", Fri:"Music", Sat:"DJ", Sun:"", Name:"Ned's Irish Gastropub", Link:"http://www.neddevines.com/events-and-live-bands.html"}, 
  {Mon:"", Tues:"", Wed:"Trivia", Thurs:"", Fri:"Live Music", Sat:"Live Music", Sun:"", Name:"The Old Brogue", Link:"https://oldbrogue.com/calendar-of-events-november"}, 
  {Mon:"", Tues:"", Wed:"Trivia", Thurs:"", Fri:"", Sat:"Karaoke", Sun:"", Name:"PJ Skidoos", Link:"http://www.pjskidoos.com/"}, 
  {Mon:"", Tues:"", Wed:"", Thurs:"", Fri:"Live Music", Sat:"", Sun:"", Name:"Northside Social Arlington (Only certain times of the year, see website)", Link:"https://www.northsidesocialva.com/arlington-events/"}, 
  {Mon:"Jazz", Tues:"Jazz", Wed:"Jazz", Thurs:"Jazz", Fri:"Jazz", Sat:"Jazz", Sun:"Jazz", Name:"Laporta's", Link:"http://www.laportas.net/live-music/"}, 
  {Mon:"Latin Dancing", Tues:"See Schedule", Wed:"Line Dancing", Thurs:"See Schedule", Fri:"See Schedule", Sat:"See Schedule", Sun:"See Schedule", Name:"The Renegade", Link:"https://renegadeva.com/arlington-clarendon-the-renegade-va-lineup"}, 
  {Mon:"See Schedule", Tues:"Trivia", Wed:"Run Club (7pm)", Thurs:"See Schedule", Fri:"See Schedule", Sat:"See Schedule", Sun:"See Schedule", Name:"Murphy's Irish Pub", Link:"https://murphyspub.com/events-live-music/"}, 
  {Mon:"See Schedule", Tues:"See Schedule", Wed:"Trivia", Thurs:"See Schedule", Fri:"See Schedule", Sat:"See Schedule", Sun:"See Schedule", Name:"The Light Horse Restaurant", Link:"https://thelighthorserestaurant.com/"}, 
  {Mon:"", Tues:"", Wed:"Jazz", Thurs:"Jazz", Fri:"Jazz", Sat:"Jazz", Sun:"", Name:"Lake Anne Coffee House", Link:"https://lakeannecoffeehouse.com/events-calendar/"}, 
  {Mon:"", Tues:"Singo Bingo, Open Mic Night", Wed:"", Thurs:"", Fri:"", Sat:"", Sun:"", Name:"Ballston Local", Link:"https://ballstonlocal.com/arlington-ballston-ballston-local-events"}
];
// END food_and_music_data